// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'home/home.route.dart';

class Flutter2Route extends NavigatorRouteNode {
  factory Flutter2Route(final NavigatorRouteNode parent) =>
      _instance ??= Flutter2Route._(parent);

  Flutter2Route._(super.parent);

  static Flutter2Route? _instance;

  late final home = HomeRoute(this);

  @override
  String get name => 'flutter2';
}
