// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

// import "package:bitverse_lite/bitverse_lite.dart" as bitverse_lite;
import 'package:flutter_thrio/flutter_thrio.dart';

import 'biz/module.dart' as biz;

class Module
    with
        ThrioModule,
        ModuleJsonDeserializer,
        ModuleJsonSerializer,
        ModuleParamScheme {
  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    navigatorLogEnabled = false;
    registerModule(biz.Module(), moduleContext);
    ///TODO register bitver-lite module
    // registerModule(bitverse_lite.Module(), moduleContext);

  }

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {}

  @override
  void onJsonSerializerRegister(final ModuleContext moduleContext) {}

  @override
  void onJsonDeserializerRegister(final ModuleContext moduleContext) {}
}
