// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter1/module.dart' as flutter1;
import 'flutter2/module.dart' as flutter2;

class Module with ThrioModule, ModuleParamScheme {
  @override
  String get key => 'biz1';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(flutter1.Module(), moduleContext);
    registerModule(flutter2.Module(), moduleContext);
  }

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme<int>('intValue');
  }
}
