// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'bb_home/module.dart' as bb_home;

class Module with ThrioModule {
  @override
  String get key => 'bb';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(bb_home.Module(), moduleContext);
  }
}
