// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'bb_home/bb_home.route.dart';

final bb = _Route();

class _Route extends NavigatorRouteNode {
  factory _Route() => _instance ??= _Route._();

  _Route._() : super.home();

  static _Route? _instance;

  late final bbHome = BbHomeRoute(this);

  @override
  String get name => 'bb';
}
