// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'main/main.route.dart';

class BbHomeRoute extends NavigatorRouteNode {
  factory BbHomeRoute(final NavigatorRouteNode parent) => _instance ??= BbHomeRoute._(parent);

  BbHomeRoute._(super.parent);

  static BbHomeRoute? _instance;

  late final main = MainRoute(this);

  @override
  String get name => 'bbHome';
}
