// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'main/module.dart' as main;

class Module with ThrioModule {
  @override
  String get key => 'bbHome';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(main.Module(), moduleContext);
  }
}
